# Generated by Django 5.0.1 on 2024-07-02 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='stat',
            field=models.ForeignKey(default='Новое', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stat', verbose_name='Статус'),
        ),
    ]
